# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c3668ce6562a406886b19fb2aa476ecc52685eb556f239216d7c86d94473af048a95b3355f9a62fec0221eb6afe5e3fe8d694aa22f3d7cf772a46691b54a9ad

test:
  secret_key_base: a7cbe0cde871daa3e6e9eaf87a350bed54f6efd13eae98808dab48f3a1c33ed46edf01e44addfed994bc398aeab61af41ce9b1500bd17a6b9252fabd20dcba3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
